CREATE TABLE t_m_user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    email      VARCHAR(255) UNIQUE,
    CONSTRAINT pk_epicuser PRIMARY KEY (id)
);