CREATE TABLE epicuser
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    email      VARCHAR(255) UNIQUE,
    password VARCHAR(72),
    CONSTRAINT pk_epicuser PRIMARY KEY (id)
);